---
# tasks file for authconfig
- set_fact:
    distro: "{{ansible_lsb.id}}-{{ansible_lsb.major_release}}"
  when: ansible_lsb.description is defined
  tags:
    - aad_adjoin
- set_fact:
    distro: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
  when: ansible_lsb.description is undefined
  tags:
    - aad_adjoin

# load version-specific variables
- block:
    - include_vars: "{{ item }}"
      with_first_found:
        - "../vars/{{distro}}.yml"
  rescue:
    - fail: msg="Variables file for distro {{ distro }} were not found."

- include: redhat.yml
  when: ansible_distribution == 'Redhat' or ansible_distribution == 'CentOS' or ansible_distribution == "Amazon"

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Common files between the dists
- name: krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - aad_krb5_conf

- name: sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart sssd
  tags:
    - aad_sssd_conf

#- name: access.conf
#  template:
#    src: access.conf.j2
#    dest: /etc/security/access.conf
#    owner: root
#    group: root
#    mode: 0640

- name: Install ssh legal thing
  copy:
    src: ssh_issue
    dest: /etc/ssh/issue
    owner: root
    group: root
    mode: 0644
  notify: restart ssh
  tags:
    - aad_ssh

- name: Update sshd_config for legal thing
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'Banner /etc/ssh/issue'
    regexp: '^(#|)Banner\ .*'
  notify: restart ssh
  tags:
    - aad_ssh

- name: Update sshd_config to allow PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication yes'
    regexp: '^(#|)PasswordAuthentication\ .*'
  notify: restart ssh
  tags:
    - aad_ssh

- name: Update sshd_config to remove old PasswordAuthentication no if exists
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'
    state: absent
  notify: restart ssh
  tags:
    - aad_ssh


#- name: enable and start sssd
#  service:
#    name: sssd
#    enabled: yes
#    state: restarted

#- name: enable and start oddjob
#  service:
#    name: oddjobd
#    enabled: yes
#    state: started
#  notify: authconfig mkhomedir

# JB: Not sure if we need this with Kerb Auth
#- name: allow password auth
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    line: 'PasswordAuthentication yes'
#    regexp: '^(#|)PasswordAuthentication\ .*'
#  notify: restart ssh

#- include: test.yml

- name: Update hostname
  lineinfile:
    dest: /etc/rc.local
    line: "sed -i \"s/ad_hostname.*/ad_hostname = $(hostname)/g\" /etc/sssd/sssd.conf"
  when: ad_build_image is defined and ad_build_image == 'yes'

- name: Join Domain
  lineinfile:
    dest: /etc/rc.local
    line:   "adcli join --no-password --domain-ou={{ authconfig_computer_ou }} --login-user={{ authconfig_sssd_name }} -S  {{ad_info.ad_server}} {{ authconfig_domain }}"
  when: ad_build_image is defined and ad_build_image == 'yes'

- name: Update sshd_config to allow PasswordAuthentication
  lineinfile:
    dest: /etc/rc.local
    line: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
  when: ad_build_image is defined and ad_build_image == 'yes'

- name: Restart sshd
  lineinfile:
    dest: /etc/rc.local
    line: "service sshd restart"
  when: ad_build_image is defined and ad_build_image == 'yes'

- meta: flush_handlers
